# -*- coding: utf-8 -*-
"""Text_evaluate_script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fvgkqP5hOIdGvhPsUFCPzsa8IUHIs8lQ
"""

import math    
import numpy as np

def evaluate_text(text, probas, threshold):
    '''
    text = [["w1", "w2", "w3"], ["w1", "w2", "w3"], ["w1", "w2", "w3"], ...]
    probas = [proba1, proba2, proba3, ...]

    len(text) == len(probas)
    '''

    if len(text) != len(probas):
        print('len(text) != len(probas)')
        return None

    word_count = sum([len(sentence) for sentence in text])
    center_probas = np.array(probas) - threshold
    # norm_probas = (center_probas -  np.nanmean(center_probas)) /  np.nanstd(center_probas)
    sig_probas = [1 / (1 + math.e ** -x) for x in center_probas]
    weight_sum = np.nansum([len(text[i]) * sig_probas[i] for i in range(len(text))])

    return weight_sum / word_count

